Build profile: -w ghc-9.6.6 -O1
In order, the following will be built (use -v for more details):
 - enclosed-exceptions-1.0.3 (test:test) (ephemeral targets)
Preprocessing test suite 'test' for enclosed-exceptions-1.0.3...
Building test suite 'test' for enclosed-exceptions-1.0.3...

<no location info>: warning: [GHC-32850] [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules for ‘enclosed-exceptions-1.0.3-inplace-test’ :
        Control.Exception.Enclosed

<no location info>: warning: [GHC-32850] [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules for ‘enclosed-exceptions-1.0.3-inplace-test’ :
        Control.Exception.Enclosed
Running 1 test suites...
Test suite test: RUNNING...

Unhandled.Exception
  const
    doesn't catch exceptions thrown from the inside [✔]
    doesn't catch exceptions thrown from the outside [✔]
    doesn't catch exceptions lazily thrown in its pure result [✔]
  fmap Right
    doesn't catch exceptions thrown from the inside [✔]
    doesn't catch exceptions thrown from the outside [✔]
    doesn't catch exceptions lazily thrown in its pure result [✔]
Control.Exception
  catch
    catches exceptions thrown from the inside [✔]
    catches exceptions thrown from the outside [✔]
    doesn't catch exceptions lazily thrown in its pure result [✔]
  try
    catches exceptions thrown from the inside [✔]
    catches exceptions thrown from the outside [✔]
    doesn't catch exceptions lazily thrown in its pure result [✔]
Control.Exception.Enclosed
  catchAny
    catches exceptions thrown from the inside [✔]
    doesn't catch exceptions thrown from the outside [✔]
    doesn't catch exceptions lazily thrown in its pure result [✔]
  catchDeep
    catches exceptions thrown from the inside [✔]
    catches exceptions thrown from the outside [✔]
    catches exceptions lazily thrown in its pure result [✔]
  tryAny
    catches exceptions thrown from the inside [✔]
    doesn't catch exceptions thrown from the outside [✔]
    doesn't catch exceptions lazily thrown in its pure result [✔]
  tryDeep
    catches exceptions thrown from the inside [✔]
    catches exceptions thrown from the outside [✔]
    catches exceptions lazily thrown in its pure result [✔]
  tryAnyDeep
    catches exceptions thrown from the inside [✔]
    doesn't catch exceptions thrown from the outside [✔]
    catches exceptions lazily thrown in its pure result [✔]

Finished in 0.0005 seconds
27 examples, 0 failures
Test suite test: PASS
Test suite logged to:
/tmp/workdir-enclosed-exceptions/enclosed-exceptions-1.0.3/dist-newstyle/build/x86_64-linux/ghc-9.6.6/enclosed-exceptions-1.0.3/t/test/test/enclosed-exceptions-1.0.3-test.log
1 of 1 test suites (1 of 1 test cases) passed.
